
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE blog (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  resume TEXT,
  thumbnail TEXT,
  slug TEXT NOT NULL,
  published_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  author TEXT NOT NULL
);