// ============================================================
// arcade-data.jsx — Real content from elfrontend.com + GitHub repo,
// bilingual + difficulty-tone variants.
// ============================================================

// ---- COPY (UI labels, bilingual) ----
const COPY = {
  en: {
    appTag: "v2.0 · ARCADE EDITION",
    stage1: "STAGE 01 · HOME",
    stage2: "STAGE 02 · ABOUT",
    stage3: "STAGE 03 · SKILLS",
    stage4: "STAGE 04 · PROJECTS",
    stage5: "STAGE 05 · TALKS",
    stage6: "STAGE 06 · VIDEOS",
    stage7: "STAGE 07 · WRITING",
    stage8: "STAGE 08 · TERMINAL",
    stage9: "STAGE 09 · CONTACT",
    nav: { home:"HOME", about:"ABOUT", skills:"SKILLS", projects:"PROJECTS", videos:"VIDEOS", blog:"BLOG", contact:"CONTACT" },
    greeting: "Hello there!",
    name: "Carlos Chao Cortes",
    handle: "@ElFrontend",
    typeLine: "What can I do for",
    typeAccent: "you?",
    intro: {
      easy:   "I'm Carlos — I make React and Next.js videos on YouTube, and I love teaching the web. Type a question below or play around in the terminal — both work!",
      medium: "Software architect · React & Next.js educator · running the ElFrontend community. Talk to my AI twin, play in the terminal, or just browse around.",
      hard:   "S.A. // React.js / Next.js. Talk to the AI or run /help in the term. No corp slop. Cuban → Madrid.",
    },
    pressStart: "PRESS START TO TALK TO CARLOS",
    askPlaceholder: "Type a question…",
    startBtn: "START",
    chips: ["Who is Carlos?", "Latest videos", "What's your stack?", "Hire for consulting"],
    chips_es_only: false,
    aboutTitle: "About",
    aboutTitleEm: "me.",
    aboutSub: "The boring stuff, in pixel form.",
    aboutBody: {
      easy:   "Cuban software architect based in Madrid, Spain. I've been building things on the web for more than 10 years — for startups, agencies, and big companies. These days I mostly teach React and Next.js on YouTube, mentor engineers one-on-one, and run the ElFrontend community where Spanish-speaking devs help each other level up. I believe great teachers are great students first, so I'm always learning out loud.",
      medium: "Cuban software architect in Madrid. 10+ years shipping web apps. I teach React/Next.js on YouTube, mentor engineers, and run the ElFrontend community for Spanish-speaking developers.",
      hard:   "MADRID-BASED. CUBAN. 10Y+ ON THE FRONTEND. SHIPS. TEACHES. MENTORS. NOT INTERESTED IN HYPE.",
    },
    facts: [
      { k:"LOCATION", v:"Madrid, Spain", color:"hot-pink" },
      { k:"FROM", v:"Cuba 🇨🇺", color:"hot-yellow" },
      { k:"YEARS XP", v:"10+ years", color:"hot-green" },
      { k:"FAVORITE STACK", v:"React + Next.js + TS", color:"brand" },
      { k:"FAVORITE COFFEE", v:"Cortado, double", color:"hot-orange" },
      { k:"PET PROJECT", v:"ElFrontend.com", color:"hot-blue" },
    ],
    nowList: {
      easy:   ["Recording a 4-part series on React 19 SSR for beginners","Writing about Tailwind v4 — what actually changed","Mentoring 8 engineers one-on-one this quarter","Building a new AI tool: Web Video Wizard","Open to one new consulting client"],
      medium: ["Recording React 19 SSR series","Writing about Tailwind v4 migration patterns","Mentoring 8 engineers this quarter","Shipping Web Video Wizard","Open for consulting"],
      hard:   ["RSC SSR S04","TW4 MIGRATE","8X MENTOR","VIDEO WIZ","CONSULT OPEN"],
    },
    statsLabels: { subs:"YT SUBS", videos:"VIDEOS", posts:"POSTS", years:"YEARS" },
    skillsTitle: "Skill",
    skillsTitleEm: "tree.",
    skillsSub: "Stuff I've leveled up over the years. Hover for details.",
    skillsLegend: { mastered:"MASTERED", strong:"STRONG", learning:"LEARNING" },
    projectsTitle: "Pet",
    projectsTitleEm: "projects.",
    projectsSub: "Things I've shipped on nights and weekends.",
    talksTitle: "Talks &",
    talksTitleEm: "courses.",
    talksSub: "Live talks, workshops and recorded courses.",
    videosTitle: "Recent",
    videosTitleEm: "videos.",
    videoCta: "SEE ALL ON YOUTUBE",
    blogTitle: "Field",
    blogTitleEm: "notes.",
    blogSub: "Mostly Spanish · sometimes English.",
    blogCta: "READ THE BLOG",
    terminalTitle: "Terminal",
    terminalTitleEm: "playground.",
    terminalSub: "Type 'help' to see what's available. Snake works. Wordle works. Probably.",
    contactTitle: "Press start to say",
    contactTitleEm: "hi.",
    contactSub: "Will reply in 1–2 days. I read every message.",
    contactName: "YOUR NAME",
    contactEmail: "YOUR EMAIL",
    contactKind: "WHAT'S THIS ABOUT?",
    contactKinds: ["Just saying hi","Consulting","Mentoring","Speaking","Collaboration","Other"],
    contactMessage: "YOUR MESSAGE",
    contactSend: "SEND MESSAGE",
    contactSent: "MESSAGE SENT · +500 XP",
    footerLeft: "© 2026 CARLOS CHAO · MADRID",
    footerRight: "INSERT COIN",
    cheatLabel: "CHEAT CODE",
    cheatHint: "↑ ↑ ↓ ↓ ← → ← → B A · TRY IT",
    konami: "★ CHEAT UNLOCKED ★",
    soundLabel: "SOUND",
    crtLabel: "CRT",
    onOff: { on:"ON", off:"OFF" },
  },
  es: {
    appTag: "v2.0 · EDICIÓN ARCADE",
    stage1: "NIVEL 01 · INICIO",
    stage2: "NIVEL 02 · SOBRE MÍ",
    stage3: "NIVEL 03 · SKILLS",
    stage4: "NIVEL 04 · PROYECTOS",
    stage5: "NIVEL 05 · CHARLAS",
    stage6: "NIVEL 06 · VIDEOS",
    stage7: "NIVEL 07 · BLOG",
    stage8: "NIVEL 08 · TERMINAL",
    stage9: "NIVEL 09 · CONTACTO",
    nav: { home:"INICIO", about:"SOBRE MÍ", skills:"SKILLS", projects:"PROYECTOS", videos:"VIDEOS", blog:"BLOG", contact:"CONTACTO" },
    greeting: "¡Hola!",
    name: "Carlos Chao Cortes",
    handle: "@ElFrontend",
    typeLine: "¿Qué puedo hacer por",
    typeAccent: "ti?",
    intro: {
      easy:   "Soy Carlos — hago videos de React y Next.js en YouTube y me encanta enseñar la web. Escribe una pregunta abajo o juega con la terminal — ¡las dos cosas funcionan!",
      medium: "Arquitecto de software · educador de React y Next.js · dirijo la comunidad ElFrontend. Habla con mi gemelo IA, juega en la terminal, o explora.",
      hard:   "S.A. // React.js / Next.js. Habla con la IA o /help en el term. Sin slop corp. Cubano → Madrid.",
    },
    pressStart: "PULSA START PARA HABLAR CON CARLOS",
    askPlaceholder: "Escribe una pregunta…",
    startBtn: "START",
    chips: ["¿Quién es Carlos?", "Últimos videos", "¿Cuál es tu stack?", "Contratar consultoría"],
    aboutTitle: "Sobre",
    aboutTitleEm: "mí.",
    aboutSub: "Lo aburrido, en píxeles.",
    aboutBody: {
      easy:   "Arquitecto de software cubano radicado en Madrid. Llevo más de 10 años construyendo cosas en la web — para startups, agencias y grandes empresas. Hoy enseño React y Next.js en YouTube, mentorizo ingenieros uno a uno y dirijo la comunidad ElFrontend, donde devs hispanohablantes se ayudan a crecer. Los buenos profesores son primero buenos estudiantes — sigo aprendiendo en voz alta.",
      medium: "Arquitecto de software cubano en Madrid. 10+ años lanzando apps web. Enseño React/Next.js en YouTube, mentorizo ingenieros y dirijo la comunidad ElFrontend.",
      hard:   "BASE: MADRID. CUBANO. 10A+ EN FRONTEND. ENVÍA. ENSEÑA. MENTORIZA. SIN HYPE.",
    },
    facts: [
      { k:"UBICACIÓN", v:"Madrid, España", color:"hot-pink" },
      { k:"ORIGEN", v:"Cuba 🇨🇺", color:"hot-yellow" },
      { k:"AÑOS XP", v:"10+ años", color:"hot-green" },
      { k:"STACK FAVORITO", v:"React + Next.js + TS", color:"brand" },
      { k:"CAFÉ FAVORITO", v:"Cortado, doble", color:"hot-orange" },
      { k:"PROYECTO PERSONAL", v:"ElFrontend.com", color:"hot-blue" },
    ],
    nowList: {
      easy:   ["Grabando serie de 4 partes sobre React 19 SSR para principiantes","Escribiendo sobre Tailwind v4 — qué cambió de verdad","Mentorizando a 8 ingenieros uno a uno este trimestre","Construyendo Web Video Wizard, una herramienta de IA","Abierto a un nuevo cliente de consultoría"],
      medium: ["Grabando serie React 19 SSR","Escribiendo sobre Tailwind v4","Mentorizando a 8 ingenieros este trimestre","Lanzando Web Video Wizard","Abierto a consultoría"],
      hard:   ["RSC SSR S04","MIGRAR TW4","8X MENTOR","VIDEO WIZ","CONSULT ABIERTO"],
    },
    statsLabels: { subs:"YT SUBS", videos:"VIDEOS", posts:"POSTS", years:"AÑOS" },
    skillsTitle: "Árbol de",
    skillsTitleEm: "skills.",
    skillsSub: "Lo que he subido de nivel. Pasa el cursor por encima.",
    skillsLegend: { mastered:"MAESTRÍA", strong:"FUERTE", learning:"APRENDIENDO" },
    projectsTitle: "Proyectos",
    projectsTitleEm: "personales.",
    projectsSub: "Cosas que he construido en noches y fines de semana.",
    talksTitle: "Charlas y",
    talksTitleEm: "cursos.",
    talksSub: "Charlas en vivo, talleres y cursos grabados.",
    videosTitle: "Videos",
    videosTitleEm: "recientes.",
    videoCta: "VER TODO EN YOUTUBE",
    blogTitle: "Notas de",
    blogTitleEm: "campo.",
    blogSub: "Mayormente en español · a veces inglés.",
    blogCta: "LEER EL BLOG",
    terminalTitle: "Terminal",
    terminalTitleEm: "playground.",
    terminalSub: "Escribe 'help' para ver los comandos. Snake funciona. Wordle también. Probablemente.",
    contactTitle: "Pulsa start para decir",
    contactTitleEm: "hola.",
    contactSub: "Respondo en 1–2 días. Leo cada mensaje.",
    contactName: "TU NOMBRE",
    contactEmail: "TU EMAIL",
    contactKind: "¿DE QUÉ VA ESTO?",
    contactKinds: ["Solo saludar","Consultoría","Mentoring","Charlas","Colaboración","Otro"],
    contactMessage: "TU MENSAJE",
    contactSend: "ENVIAR MENSAJE",
    contactSent: "MENSAJE ENVIADO · +500 XP",
    footerLeft: "© 2026 CARLOS CHAO · MADRID",
    footerRight: "INSERTA UNA MONEDA",
    cheatLabel: "TRUCO",
    cheatHint: "↑ ↑ ↓ ↓ ← → ← → B A · PRUÉBALO",
    konami: "★ TRUCO DESBLOQUEADO ★",
    soundLabel: "SONIDO",
    crtLabel: "CRT",
    onOff: { on:"ON", off:"OFF" },
  },
};

// ---- VIDEOS (top from elfrontend.com & channel) ----
const VIDEOS = [
  { id:'v1', yt:'mmt24cot0vg',
    title:{ en:"My AI development framework (2026)", es:"Mi Framework de Desarrollo con IA (2026)" },
    meta:"24K · 2 weeks ago", duration:"18:42", new:true,
    thumb:"https://i.ytimg.com/vi/mmt24cot0vg/hqdefault.jpg" },
  { id:'v2', yt:'AVIZM0Pl7JI',
    title:{ en:"Coding is tied to math — but math isn't required to code", es:"La programación está muy relacionada con la matemática pero no es del todo necesaria para programar" },
    meta:"12K · 1 month ago", duration:"24:08", new:false,
    thumb:"https://i.ytimg.com/vi/AVIZM0Pl7JI/hqdefault.jpg" },
  { id:'v3', yt:'t-zskvCWLIA',
    title:{ en:"Álvaro's first job in the United States", es:"El primer trabajo de Álvaro en Estados Unidos" },
    meta:"8.4K · 1 month ago", duration:"32:11", new:false,
    thumb:"https://i.ytimg.com/vi/t-zskvCWLIA/hqdefault.jpg" },
  { id:'v4', yt:'react19',
    title:{ en:"Stop fighting React 19 — embrace the new SSR model", es:"Deja de pelear con React 19 — abraza el nuevo SSR" },
    meta:"15K · 2 months ago", duration:"22:50", new:false,
    thumb:"assets/blog/react19-ssr.webp" },
];

// ---- BLOG POSTS ----
const BLOG = [
  { id:'b1', slug:'build-web-video-wizard',
    title:{ en:"I built my own AI video trimming tool because paid ones were too expensive", es:"Construí mi propia herramienta de recorte de video con IA porque las de pago eran demasiado caras" },
    date:{ en:"Apr 2026", es:"Abr 2026" }, read:"15 min", tag:"AI", thumb:"assets/blog/web3.webp" },
  { id:'b2', slug:'react-19-server-side-rendering',
    title:{ en:"Best practices for React Server Components in React 19", es:"Mejores prácticas para React Server Components en React 19 ✨🚀" },
    date:{ en:"Mar 2026", es:"Mar 2026" }, read:"12 min", tag:"React", thumb:"assets/blog/react19-ssr.webp" },
  { id:'b3', slug:'software-design-patterns',
    title:{ en:"Fundamental principles and patterns in software design", es:"Principios y patrones fundamentales en el diseño de software" },
    date:{ en:"Feb 2026", es:"Feb 2026" }, read:"18 min", tag:"Theory", thumb:"assets/blog/effective-software-estimations.webp" },
  { id:'b4', slug:'tailwindcss-v4',
    title:{ en:"Tailwind CSS 3 vs 4 — what changed and how it affects your workflow", es:"Tailwind CSS 3 vs 4 — ¿qué ha cambiado y cómo afecta tu flujo?" },
    date:{ en:"Jan 2026", es:"Ene 2026" }, read:"8 min", tag:"CSS", thumb:"assets/blog/tailwind3-4.webp" },
  { id:'b5', slug:'effective-software-estimations',
    title:{ en:"Effective software estimations", es:"Estimaciones efectivas de software" },
    date:{ en:"Dec 2025", es:"Dic 2025" }, read:"7 min", tag:"Process", thumb:"assets/blog/effective-software-estimations.webp" },
  { id:'b6', slug:'trunk-base-development',
    title:{ en:"Trunk-based development for small teams", es:"Trunk-based development para equipos pequeños" },
    date:{ en:"Nov 2025", es:"Nov 2025" }, read:"6 min", tag:"Workflow", thumb:"assets/blog/trunk-base-development.webp" },
];

// ---- SKILLS — pixel skill tree ----
// level: 3 = mastered, 2 = strong, 1 = learning
const SKILL_GROUPS = [
  {
    id:'lang', name:{ en:"LANGUAGES", es:"LENGUAJES" }, color:"brand",
    skills:[
      { name:"JavaScript", level:3, years:"10+y" },
      { name:"TypeScript", level:3, years:"7y" },
      { name:"Python", level:2, years:"5y" },
      { name:"Java", level:2, years:"4y" },
      { name:"Rust", level:1, years:"1y" },
    ],
  },
  {
    id:'fw', name:{ en:"FRAMEWORKS", es:"FRAMEWORKS" }, color:"hot-pink",
    skills:[
      { name:"React", level:3, years:"9y" },
      { name:"Next.js", level:3, years:"6y" },
      { name:"Vue", level:2, years:"3y" },
      { name:"Express", level:3, years:"8y" },
      { name:"Django", level:2, years:"3y" },
      { name:"Astro", level:1, years:"1y" },
    ],
  },
  {
    id:'tools', name:{ en:"TOOLS & CLOUD", es:"HERRAMIENTAS" }, color:"hot-green",
    skills:[
      { name:"Git", level:3, years:"10y" },
      { name:"Docker", level:3, years:"6y" },
      { name:"AWS", level:2, years:"5y" },
      { name:"Vercel", level:3, years:"4y" },
      { name:"Postgres", level:2, years:"6y" },
      { name:"Redis", level:2, years:"4y" },
    ],
  },
  {
    id:'soft', name:{ en:"SOFT SKILLS", es:"HABILIDADES BLANDAS" }, color:"hot-yellow",
    skills:[
      { name:"Teaching", level:3, years:"10y" },
      { name:"Mentoring", level:3, years:"7y" },
      { name:"Public Speaking", level:2, years:"5y" },
      { name:"Writing", level:2, years:"4y" },
    ],
  },
];

// ---- PROJECTS ----
const PROJECTS = [
  { id:'p1', name:"Web Video Wizard", year:"2026", color:"hot-pink", icon:"film",
    tag:{ en:"AI VIDEO TRIMMING", es:"RECORTE IA" },
    desc:{ en:"My own AI-powered video trimming tool. Built because paid alternatives were ridiculously expensive.", es:"Mi propia herramienta de recorte de video con IA. La construí porque las alternativas pagas eran ridículamente caras." },
    stack:["Next.js", "FFmpeg", "OpenAI", "Tailwind"],
    href:"https://elfrontend.com/blog/build-web-video-wizard",
  },
  { id:'p2', name:"ElFrontend.com", year:"2024-26", color:"brand", icon:"home",
    tag:{ en:"PERSONAL SITE", es:"SITIO PERSONAL" },
    desc:{ en:"This site! AI chat hero, working terminal with Snake & Wordle, switchable backgrounds, MDX blog.", es:"¡Este sitio! Hero con chat IA, terminal con Snake y Wordle, fondos cambiables, blog en MDX." },
    stack:["Next.js 16", "Tailwind v4", "shadcn/ui", "Motion"],
    href:"https://elfrontend.com",
  },
  { id:'p3', name:"ElFrontend Community", year:"2023+", color:"hot-yellow", icon:"users",
    tag:{ en:"DEV COMMUNITY", es:"COMUNIDAD DEV" },
    desc:{ en:"Spanish-speaking community of frontend developers helping each other level up. YouTube + Discord + meetups.", es:"Comunidad hispana de devs frontend que se ayudan a crecer. YouTube + Discord + meetups." },
    stack:["YouTube", "Discord", "Twitch"],
    href:"https://youtube.com/@ElFrontend",
  },
  { id:'p4', name:"OSS Contributions", year:"ongoing", color:"hot-green", icon:"github",
    tag:{ en:"OPEN SOURCE", es:"CÓDIGO ABIERTO" },
    desc:{ en:"Random contributions to React ecosystem libraries, dev tooling, and small utility packages.", es:"Contribuciones varias al ecosistema React, herramientas de desarrollo y paquetes utilitarios pequeños." },
    stack:["TypeScript", "GitHub"],
    href:"https://github.com/el-frontend",
  },
];

// ---- TALKS & COURSES ----
const TALKS = [
  { id:'t1', kind:'TALK', date:{en:"May 2026", es:"May 2026"}, where:"React Madrid",
    title:{ en:"Stop fighting React 19", es:"Deja de pelear con React 19" },
    meta:{ en:"45 min · Spanish", es:"45 min · Español" }, color:"hot-pink" },
  { id:'t2', kind:'COURSE', date:{en:"Mar 2026", es:"Mar 2026"}, where:"Domestika",
    title:{ en:"Production Next.js for non-juniors", es:"Next.js en producción para no juniors" },
    meta:{ en:"6 hours · Spanish · 12 lessons", es:"6 horas · Español · 12 lecciones"}, color:"brand" },
  { id:'t3', kind:'WORKSHOP', date:{en:"Feb 2026", es:"Feb 2026"}, where:"BcnDev",
    title:{ en:"Tailwind v4 migration workshop", es:"Taller de migración a Tailwind v4" },
    meta:{ en:"3 hours · live coding", es:"3 horas · en vivo"}, color:"hot-yellow" },
  { id:'t4', kind:'TALK', date:{en:"Nov 2025", es:"Nov 2025"}, where:"JSDay Spain",
    title:{ en:"AI tools that actually help frontend devs", es:"Herramientas de IA que sí ayudan a los devs frontend" },
    meta:{ en:"30 min · Spanish", es:"30 min · Español" }, color:"hot-green" },
];

// ---- STATS ----
const STATS = [
  { key:"subs",   val:"42.1K", color:"hot-pink" },
  { key:"videos", val:"187",   color:"hot-yellow" },
  { key:"posts",  val:"64",    color:"hot-green" },
  { key:"years",  val:"10+",   color:"brand" },
];

// ---- SOCIAL LINKS ----
const SOCIALS = [
  { id:'youtube',  label:"YouTube",  href:"https://youtube.com/@ElFrontend",  color:"hot-red" },
  { id:'github',   label:"GitHub",   href:"https://github.com/el-frontend",   color:"ink" },
  { id:'linkedin', label:"LinkedIn", href:"https://linkedin.com/in/carlos-chao", color:"hot-blue" },
  { id:'twitch',   label:"Twitch",   href:"https://twitch.tv/elfrontend",     color:"brand" },
  { id:'instagram',label:"Instagram",href:"https://instagram.com/elfrontend", color:"hot-pink" },
  { id:'x',        label:"X",        href:"https://x.com/elfrontend",         color:"ink" },
];

Object.assign(window, { COPY, VIDEOS, BLOG, SKILL_GROUPS, PROJECTS, TALKS, STATS, SOCIALS });
